[package]
name = "macro_railroad"
version = "0.1.8"
authors = ["Lukas Lueg <lukas.lueg@gmail.com>"]
edition = "2024"
license = "MIT"
description = "A library to generate syntax diagrams for Rust macros"
repository = "https://github.com/lukaslueg/macro_railroad"
readme = "README.md"
exclude = ["examples/*.jpeg", "examples/*.jpg", "examples/*.svg", "examples/*.html"]

[dependencies]
syn = { version = "2.0", features = ["full", "parsing", "extra-traits"], default-features=false }
railroad = { version = "0.3.6", default-features=false }
proc-macro2 = { version = "1.0", default-features=false }

[dev-dependencies]
quote = { version = "1.0", default-features = false }
railroad_verification = "0.1"
criterion = { version = "0.8", default-features = false, features = ["cargo_bench_support"] }

[[bench]]
name = "to_diagram"
harness = false

[features]
visual-debug = ["railroad/visual-debug"]
resvg = ["railroad/resvg"]
